# Generated by Django 3.2.5 on 2022-03-15 04:37

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Name')),
                ('abbrev', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Abbreviation')),
                ('logo', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Logo')),
                ('retirement', models.IntegerField(blank=True, default=None, null=True, verbose_name='Retirement')),
                ('debut', models.IntegerField(blank=True, default=None, null=True, verbose_name='Debut')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('fav_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tippingcomp.team', verbose_name='Favourite Team')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Updated')),
                ('round', models.IntegerField(blank=True, default=None, null=True, verbose_name='Round')),
                ('roundname', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Round Name')),
                ('tz', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Timezone')),
                ('venue', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Venue')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Match Date')),
                ('hteam', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Home Team')),
                ('ateam', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Away Team')),
                ('hteamid', models.IntegerField(blank=True, default=None, null=True, verbose_name='Home Team ID')),
                ('ateamid', models.IntegerField(blank=True, default=None, null=True, verbose_name='Away Team ID')),
                ('winnerteamid', models.IntegerField(blank=True, default=None, null=True, verbose_name='Winner Team ID')),
                ('winner', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Winner')),
                ('hscore', models.IntegerField(blank=True, default=None, null=True, verbose_name='Home Team Score')),
                ('hgoals', models.IntegerField(blank=True, default=None, null=True, verbose_name='Home Team Goals')),
                ('hbehinds', models.IntegerField(blank=True, default=None, null=True, verbose_name='Home Team Behinds')),
                ('ascore', models.IntegerField(blank=True, default=None, null=True, verbose_name='Away Team Score')),
                ('agoals', models.IntegerField(blank=True, default=None, null=True, verbose_name='Away Team Goals')),
                ('abehinds', models.IntegerField(blank=True, default=None, null=True, verbose_name='Away Team Behinds')),
                ('is_grand_final', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2022)),
                ('complete', models.BooleanField(default=False)),
                ('localtime', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('away_team_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='tippingcomp.team', verbose_name='Away Team Key')),
                ('home_team_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tippingcomp.team', verbose_name='Home Team Key')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.BooleanField(max_length=200, verbose_name='Bet')),
                ('result', models.IntegerField(blank=True, default=None, null=True, verbose_name='Result')),
                ('match', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tippingcomp.match')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tippingcomp.user')),
            ],
        ),
    ]
