# Generated by Django 3.2.5 on 2022-05-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippingcomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='timestr',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='timestr'),
        ),
        migrations.AlterField(
            model_name='match',
            name='localtime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Local Time'),
        ),
    ]
