# Generated by Django 4.1.3 on 2022-12-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tippingcomp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="unixtime",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Unix Time"
            ),
        ),
    ]
