# Generated by Django 4.1.3 on 2022-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tippingcomp", "0002_match_unixtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="is_final",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Is Final"
            ),
        ),
    ]
